name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Producao  # Altere para o nome do branch que você está usando
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Producao  # Altere para o nome do branch que você está usando

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish --configuration Release --output ./bin/Release/net8.0/publish
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  
          action: 'upload'
          app_location: '/CisReg_Website'  
          api_location: '' 
          output_location: 'bin/Release/net8.0/publish'  
